import React from "react";
import SharedLayout from "../_modules/_shared/layout/sharedLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Self-Service Portal | Tickets",
  description: "Generated by create next app",
};

const TicketsLayout = ({ children }: React.PropsWithChildren) => {
  return <SharedLayout>{children}</SharedLayout>;
};

export default TicketsLayout;
