import React from "react";
import SharedLayout from "../_modules/_shared/layout/sharedLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Self-Service Portal | Charts",
  description: "Generated by create next app",
};

const ChartsLayout = ({ children }: React.PropsWithChildren) => {
  return <SharedLayout>{children}</SharedLayout>;
};

export default ChartsLayout;
