import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./_utils/_provider/ReactQueryProvider";
import { ConfigProvider } from "antd";

import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EN Self-Service Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#1d364e",
              colorBgLayout: "#ffffff",
              colorText: "#1d364e",
              colorPrimaryText: "1d364e",
              colorPrimaryBg: "#ffffff",
            },
          }}
        >
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ConfigProvider>
        <Script
          id="ze-snippet"
          src="https://static.zdassets.com/ekr/snippet.js?key=3f379446-cfea-43dc-b0f8-8050a47f8bfa"
        />
      </body>
    </html>
  );
}
