import React, { Suspense } from "react";
import SharedLayout from "../_modules/_shared/layout/sharedLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Self-Service Portal | Page Management",
  description: "Generated by create next app",
};

const IRLayout = ({ children }: React.PropsWithChildren) => {
  return (
    <Suspense fallback={null}>
      <SharedLayout>{children}</SharedLayout>
    </Suspense>
  );
};

export default IRLayout;
